name: Test

on:
  release:
    types: [prereleased]

jobs:
  test:
    if: ${{ github.event.release.prerelease && startsWith(github.event.release.tag_name, 'v1') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

