name: Test

on:
  release:
    types: [prereleased]

jobs:
  test:
    if: ${{ startsWith(github.event.release.tag_name, 'v1') }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "Hello World!"
      
  post-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!2"

